os: osx
language: swift
osx_image: xcode16.1
xcode_project: App.xcodeproj
xcode_scheme: App
xcode_sdk: iphonesimulator
xcode_destination: generic/platform=iOS Simulator
after_success:
  - bash <(curl -s https://codecov.io/bash)
